<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\VideoContentReviews.DataAccess\VideoContentReviews.DataAccess.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="User\Managers\" />
      <Folder Include="User\Providers\" />
    </ItemGroup>

</Project>
